name: ðŸ†™ Release File Check

on:
  pull_request:
    branches:
    - main
    paths:
    - "gqlauth/**"
    - ".github/workflows/release_check.yml"
    - "pyproject.toml"

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Check release
        id: check_release
        run: |
          python -m pip install --upgrade pip
          python -m pip install githubrelease httpx==0.18.2 autopub
          echo "release=$(autopub check)" >> $GITHUB_OUTPUT

      - uses: mshick/add-pr-comment@v2
        if: ${{ steps.check_release.outputs.release!='' }}
        name: add failed release comment
        with:
          repo-token: ${{ secrets.BOT_TOKEN }}
          message: |
            ${{ steps.check_release.outputs.release }}
      - uses: mshick/add-pr-comment@v2
        if: ${{ steps.check_release.outputs.release=='' }}
        name: add release comment
        with:
          repo-token: ${{ secrets.BOT_TOKEN }}
          message-path: ./RELEASE.md

      - name: fail if check failed
        if: ${{ steps.check_release.outputs.release!='' }}
        run: |
          exit 1
